export const schools: string[] = [
  // South Africa
  "University of Cape Town",
  "University of the Witwatersrand",
  "Stellenbosch University",
  "University of Pretoria",
  "University of Johannesburg",
  "University of KwaZulu-Natal",
  "Rhodes University",
  "North-West University",
  "University of the Western Cape",
  "University of the Free State",
  "Nelson Mandela University",
  "University of South Africa (UNISA)",
  "Tshwane University of Technology",
  "Cape Peninsula University of Technology",
  "Durban University of Technology",
  "University of Limpopo",
  "University of Venda",
  "University of Fort Hare",
  "Sol Plaatje University",
  "University of Mpumalanga",
  "Vaal University of Technology",
  "Central University of Technology",
  "Walter Sisulu University",
  "Sefako Makgatho Health Sciences University",
  "Mangosuthu University of Technology",

  // Africa (selected)
  "University of Nairobi",
  "Makerere University",
  "University of Lagos",
  "University of Ibadan",
  "Obafemi Awolowo University",
  "Covenant University",
  "Ashesi University",
  "University of Ghana",
  "Cairo University",
  "American University in Cairo",
  "University of Rwanda",
  "Addis Ababa University",
  "University of Botswana",

  // Global
  "Massachusetts Institute of Technology (MIT)",
  "Stanford University",
  "Harvard University",
  "Carnegie Mellon University",
  "University of California, Berkeley",
  "University of California, Los Angeles (UCLA)",
  "California Institute of Technology (Caltech)",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "Cornell University",
  "University of Chicago",
  "University of Pennsylvania",
  "University of Michigan",
  "University of Washington",
  "Georgia Institute of Technology",
  "University of Illinois Urbana-Champaign",
  "University of Texas at Austin",
  "New York University",
  "University of Toronto",
  "University of British Columbia",
  "McGill University",
  "University of Waterloo",
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London (UCL)",
  "London School of Economics",
  "King's College London",
  "University of Edinburgh",
  "ETH Zurich",
  "EPFL",
  "Technical University of Munich",
  "Sorbonne University",
  "Delft University of Technology",
  "KTH Royal Institute of Technology",
  "Tsinghua University",
  "Peking University",
  "National University of Singapore",
  "Nanyang Technological University",
  "University of Tokyo",
  "Kyoto University",
  "Seoul National University",
  "KAIST",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Madras",
  "Indian Institute of Science",
  "University of Melbourne",
  "University of Sydney",
  "Australian National University",
  "University of Auckland",
];
